#
# cyrange
# https://gitlab.cylab.be/cylab/cyrange-web
#
# this docker-compose can be used to run a development environment
#

version: "3"
services:
  cyrange:
    image: cylab/laravel-dev
    depends_on:
      - redis
      - mysql
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    env_file: .env
    environment:
      WAIT_HOSTS: mysql:3306, guacamole-mysql:3306

  queue:
    image: cylab/laravel-dev
    depends_on:
      - cyrange
    volumes:
      - .:/var/www/html
    command: ["php", "artisan", "queue:work", "--verbose", "--tries=3", "--timeout=60"]
    restart: unless-stopped
    env_file: .env
    environment:
      WAIT_HOSTS: cyrange:80

  scheduler:
    image: cylab/laravel-dev
    depends_on:
      - cyrange
    volumes:
      - .:/var/www/html
    command: ["/scheduler.sh"]
    env_file: .env
    environment:
      WAIT_HOSTS: cyrange:80

  node:
    image: node:16.15.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: /bin/sh -c "npm install && npm run watch-poll"
    depends_on:
      - cyrange

  redis:
    image: redis:4-alpine
    volumes:
      - ./volumes/redis:/data

  mysql:
    image: mysql:5.7
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cyrange

  guacd:
    image: guacamole/guacd:1.3.0

  guacamole:
    image: guacamole/guacamole:1.3.0
    depends_on:
      - guacd
      - guacamole-mysql
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guacamole-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: guacamole
    ports:
      - 8081:8080

  guacamole-mysql:
    image: mysql:5.7
    # to create the mysql tables when the container is created
    # https://iamvickyav.medium.com/mysql-init-script-on-docker-compose-e53677102e48
    volumes:
      - ./001-create-schema.sql:/docker-entrypoint-initdb.d/001.sql
      - ./volumes/guacamole-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guacamole

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

