version: '3'

services:
  guacamole:
    image: mysql:5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: guacamole
      MYSQL_DATABASE: guacamole
    ports:
      - "3306:3306"
    # to create the mysql tables when the container is created
    # https://iamvickyav.medium.com/mysql-init-script-on-docker-compose-e53677102e48
    volumes:
      - "./001-create-schema.sql:/docker-entrypoint-initdb.d/001.sql"
